---

cho_chikun:
  name: Cho Chikun
  id: cho_chikun
  dialog: cho_chikun
  description: 
  - {speaker: LOGIK, text: "Ein verrück aussehender Mann, irgendwie kommt er mir bekannt vor"}
  
passant: 
  name: Passant
  id: passant
  dialog: strangeGuysDialog
  description:
  - {speaker: PERZEPTION, text: "Ein komischer Passant, der wild in der Gegend umherzeigt"}
  roomDescription:
  - {speaker: PERZEPTION, text: "Ein Passant aus der komischen Gruppe an Passanten, die wild in der Gegen umherzeigen."}

konstantin_thron:
  name: Konstantin Thron
  id: konstantin_thron
  dialog: konstantinDialog
  description:
  - {speaker: PERZEPTION, text: "Herr Thron wirkt etwas eingebildet."}
  roomDescription:
  - {speaker: PERZEPTION, text: "Ein Mann steht an eine Wand gelehnt, ließt Zeitung und raucht Pfeife."}
  items:
    - [basic_cigaretts, { }]
    - [basic_wine, { }]

ticketVerkäufer:
  name: der Ticketverkäufer
  id: ticketVerkäufer
  dialog: ticketVerkäuferDialog

besoffene_frau:
  name: eine besoffene Frau
  id: besoffene_frau
  hp: 40
  strength: 16
  roomDescription:
  - {speaker: PERZEPTION, text: "Eine anscheinend bewusstlose Frau liegt in einer Alkoholpfütze, eine noch glühene, halb abgebrannte Zigarette befindet sich zwischen ihren Fingern.", post_otEvents: [talk besoffene frau]}
  description:
  - {speaker: PERZEPTION, text: "Eine betrunkene Frau. Sie sieht von Alkohol mitgenommen aus, aber dahinter erkennt man, etwas von einer beeindruckenden Schönheit... und Stärker.", post_pEvents: [talk besoffene frau]}
  attacks:
    kick: Normal Kick
    punsch: Punsch
  dialog: drunkWomanDialog

