---

- name: Passant
  id: passant
  dialog: strangeGuysDialog

- name: Konstantin Thron
  id: konstantin_thron
  dialog: konstantinDialog
  description:
  - {speaker: PERZEPTION, text: "Herr Thron wirkt etwas eingebildet."}
  roomDescription:
  - {speaker: PERZEPTION, text: "Ein Mann steht an eine Wand gelehnt, ließt Zeitung und raucht Pfeife."}
  items:
    - [basic_cigaretts, { }]
    - [basic_wine, { }]

- name: der Ticketverkäufer
  id: ticketVerkäufer
  dialog: ticketVerkäuferDialog

- name: eine besoffene Frau
  id: besoffene_frau
  hp: 40
  strength: 16
  roomDescription:
  - {speaker: PERZEPTION, text: "Eine anscheinend bewusstlose Frau liegt in einer Alkoholpfütze, eine noch glühene, halb abgebrannte Zigarette befindet sich zwischen ihren Fingern.", otEvents: [talk besoffene frau]}
  description:
  - {speaker: PERZEPTION, text: "Eine betrunkene Frau. Sie sieht von Alkohol mitgenommen aus, aber dahinter erkennt man, etwas von einer beeindruckenden Schönheit... und Stärker.", pEvents: [talk besoffene frau]}
  attacks:
    kick: Normal Kick
    punsch: Punsch
  dialog: drunkWomanDialog

