#ifndef DERZUG_SRC_GUI_SRC_UTIL_ERRORCODES
#define DERZUG_SRC_GUI_SRC_UTIL_ERRORCODES

enum ErrorCodes
{
  SUCCESS = 0,
  WRONG_FORMAT = 1,
  ACCESS_DENIED = 2,
  PATH_NOT_FOUND = 3,
  NOT_ALLOWED = 4,
  ALREADY_EXISTS = 5,
  FAILED = 6,
  NO_USER = 7,
  NO_WORLD = 8,
  GAME_NOT_RUNNING = 9
};


#endif
