---

- name: Passant1
  id: passant1
  dialog: strangeGuysDialog
- name: Passant2
  id: passant2
  dialog: strangeGuysDialog
- name: Passant3
  id: passant3
  dialog: strangeGuysDialog

- name: Konstantin Thron
  id: konstantin_thron
  dialog: konstantinDialog
  description:
  - {speaker: PERZEPTION, text: "Herr Thron wirkt etwas eingebildet."}
  roomDescription:
  - {speaker: PERZEPTION, text: "Ein Mann steht an eine Wand gelehnt, ließt Zeitung und raucht Pfeife."}
  items:
    - [basic_cigaretts, { }]
    - [basic_wine, { }]

- name: Passant1
  id: passant4
  dialog: strangeGuysDialog
- name: Passant2
  id: passant5
  dialog: strangeGuysDialog
- name: Passant3
  id: passant6
  dialog: strangeGuysDialog

- name: Ticketverkäufer
  id: ticketVerkäufer
  dialog: ticketVerkäuferDialog

- name: Besoffener Frau
  id: besoffene_frau
  hp: 40
  strength: 16
  roomDescription:
  - {speaker: PERZEPTION, text: "Eine anscheinend bewusstlose Frau liegt in einer Alkoholpfütze, eine noch glühene, halb abgebrannte Zigarette befindet sich zwischen ihren Fingern."}
  description:
  - {speaker: PERZEPTION, text: "Eine betrunkene Frau. Sie sieht von Alkohol mitgenommen aus, aber dahinter erkennt man, etwas von einer beeindruckenden Schönheit... und Stärker."}
  attacks:
    kick: Normal Kick
    punsch: Punsch
  dialog: drunkWomanDialog

- name: Passant1
  id: passant7
  dialog: strangeGuysDialog
- name: Passant2
  id: passant8
  dialog: strangeGuysDialog
- name: Passant3
  id: passant9
  dialog: strangeGuysDialog

