---

- name: "Eingangshalle"
  id: bahnhof_eingangshalle
  description: 
    - {speaker: PERZEPTION, text: "Die Eingangshalle des sog. \"Moskauer Bahnhofs\" in Sankt Petersburg ist ein eindrucksvolles Gebilde. Tausende Passanten wandern umher, es herscht Trubel und Lärm und dazu glänzt die architektonische Meisterleistung eines Konstantin Thron von allen Seiten auf einen herab. Nach Norden geht es zu den Gleisen, im Süden liegt der Ausgang und nach Osten geht es zu einer Nebenhalle."}
    - {speaker: PERZEPTION, text: "Drei Passanten stehen merkwürdig gekleidet in einer Ecke der Eingangshalle nahe den Gleisen und deuten wild umher.", deps: {perzeption: ">=1"}, updates: {perzeption: 1}}
  exits:
    bahnhof_fernzüge: {name: Fernzügen, prep: zu den}
    bahnhof_nebenhalle: {name: Nebenhalle, prep: zur }
    ausgang: { name: Ausgang, prep: zum }
  characters:
    passant1: { }
    passant2: { }
    passant3: { }
    zombie: {ep: 15}
  items:
    buch_PdG: { }
    basic_stick: { hidden: true }
    basic_sword: { hidden: true }
    basic_wine: { hidden: true, amount: 2 }
    basic_cigaretts: { hidden: true, amount: 2 }
  details:
    - name: Small box
      id: trainstation_small-box
      description: 
        - {speaker: PERZEPTION, text: "A small wooden box stands in the left corner of the room."}
      look: in
      items:
        basic_wine: Wine
        basic_wine2: Wine
        basic_cigaretts: A pack of Cigaretts
        basic_sword: Basic Sword
        basic_stick: Stick


- name: Fernzüge 
  id: bahnhof_fernzüge
  description: 
    - {speaker: PERZEPTION, text: "Hier ist der Lärm Ohrenbetäubend, die Dampflokomotiven haben den ganzen bereich vernebelt. Schwitzige, ölbeschmierte Arbeiter reparieren notdürftig Züge, reiche Familien rennen in aufwändigen Gewändern ihren Packburschen davon, es herscht wildes Treiben. Richtung Noden liegen die Gleise des Bahnhofs, nach Süden geht es zurück zur Eingangshalle"}
  exits:
    gleis1: { name: "Gleis 1", prep: zu}
    gleis2: { name: "Gleis 2", prep: zu}
    gleis3: { name: "Gleis 3", prep: zu}
    gleis4: { name: "Gleis 4", prep: zu}
    gleis5: { name: "Gleis 5", prep: zu}
    bahnhof_eingangshalle: { name: Eingangshalle, prep: zur }

- name: Nebenhalle
  id: bahnhof_nebenhalle 
  description: 
    - {speaker: PERZEPTION, text: "Hier ist es etwas ruhiger und leerer. Aber die Personen hier kommen dir unheimlicher und auch sonderbarer vor. Ah und hier sind auch die Toiletten."}
    - {speaker: PERZEPTION, text: "Wieder stehen drei Passanten merkwürdig gekleidet in einer Ecke im Norden-Westen und deuten wild umher."}
  exits:
    bahnhof_eingangshalle: { name: Eingangshalle, prep: zur}
    bahnhof_toiletten: { name: Toiletten, prep: zu den}
  characters:
    passant4: { }
    passant5: { }
    passant6: { }
    konstantin_thron: { }

- name: Ausgang
  id: ausgang
  description:
  - {speaker: PERZEPTION, text: "You have left this world"}
  exits:
    bahnhof_eingangshalle: { name: Eingangshalle }

- name: Toiletten
  id: bahnhof_toiletten 
  description: 
    - {speaker: PERZEPTION, text: "Versifte Toiletten, aber endlich Ruhe, hier scheint niemand zu sein. Zwei Türen führen zu den Männer- bzw. Frauentoiletten. Im Westen geht es zurück ins Nebengebäude."}
  exits:
    bahnhof_maennerToilette: { name: Männer-Toilette, prep: zur}
    bahnhof_frauenToilette: { name: Frauen-Toilette, prep: zur}
    bahnhof_nebenhalle: { name: Nebenhalle, prep: zur}

- name: Männer-Toilette
  id: bahnhof_maennerToilette
  description: 
    - {speaker: PERZEPTION, text: "Die Männertoilette, sie ist erstaunlich sauber, in einer Ecke liegen einige zerdrückte Kippenstummel, aber es riecht nicht nach Rauch."}
  exits:
    bahnhof_toiletten: { name: Vorraum, prep: zurück zum }
  characters:
    ticketVerkäufer: { }

- name: Frauen-Toilette
  id: bahnhof_frauenToilette
  description: 
    - {speaker: PERZEPTION, text: "Die Frauentoilette:  es stinkt nach Alkohol, Kippen und Sex. Der Boden ist voller Alkohol und Glasscherben."}
    - {speaker: PERZEPTION, text: Eine besoffene Frau schnarcht laut auf der Toilette. Die Tür steht offen. Dich beschleicht der Gedanke, dass sie für das Chaos, den Geruch und die Scherben verantwortlich ist."}
  exits:
    bahnhof_toiletten: { name: Vorraum, prep: zurück zum }
  characters:
    besoffene_frau: { } 


- name: "Gleis 1"
  id: gleis1
  description: 
    - {speaker: PERZEPTION, text: "Hier ist es laut, die Züge fahren in irgendwelche Städte, die du nicht kennst."}
  exits: 
    bahnhof_fernzüge: { name: Zurück zu den Gleisen/ Fernzügen }

- name: "Gleis 2"
  id: gleis2
  description: 
    - {speaker: PERZEPTION, text: "Hier ist es laut, die Züge fahren in irgendwelche Städte, die du nicht kennst."}
  exits: 
    bahnhof_fernzüge: { name: Zurück zu den Gleisen/ Fernzügen }

- name: "Gleis 3"
  id: gleis3
  description: 
    - {speaker: PERZEPTION, text: "Ah, Gleis 3. Hier fährt dein Zug nach Moskau. Es ist selbstsam leer."}
  exits: 
    bahnhof_fernzüge: { name: Zurück zu den Gleisen/ Fernzügen }

- name: "Gleis 4"
  id: gleis4
  description: 
    - {speaker: PERZEPTION, text: "Hier ist es laut, die Züge fahren in irgendwelche Städte, die du nicht kennst."}
  exits: 
    bahnhof_fernzüge: { name: Zurück zu den Gleisen/ Fernzügen }

- name: "Gleis 5"
  id: gleis5
  description: 
    - {speaker: PERZEPTION, text: "Hier ist es laut, die Züge fahren in irgendwelche Städte, die du nicht kennst."}
    - {speaker: PERZEPTION, text: "Wieder stehen drei Passanten merkwürdig gekleidet in einer Ecke und deuten wild umher."}
  exits: 
    bahnhof_fernzüge: { name: Zurück zu den Gleisen/ Fernzügen}
  characters:
    passant7: { }
    passant8: { }
    passant9: { } 
