---

- name: "Eingangshalle"
  id: bahnhof_eingangshalle
  description: 
    - PERZEPTION;Die Eingangshalle des sog. \"Moskauer Bahnhofs\" in Sankt Petersburg ist ein eindrucksvolles Gebilde. Tausende Passanten wandern umher, es herscht Trubel und Lärm und dazu glänzt die architektonische Meisterleistung eines Konstantin Thron von allen Seiten auf einen herab. Nach Norden geht es zu den Gleisen, im Süden liegt der Ausgang und nach Osten geht es zu einer Nebenhalle.
  exits:
    bahnhof_gleise: {name: Fernzügen, prep: zu den}
    bahnhof_nebenhalle: {name: Nebenhalle, prep: zur }
    ausgang: { name: Ausgang, prep: zum }
  characters:
    - name: Passant1
      id: passant1
      description: 
        - 'PERZEPTION_1;Drei Passanten stehen merkwürdig gekleidet in einer Ecke der Eingangshalle nahe den Gleisen und deuten wild umher.;{};{"perzeption":1}'
      dialog: strangeGuysDialog
    - name: Passant2
      id: passant2
      dialog: strangeGuysDialog
    - name: Passant3
      id: passant3
      dialog: strangeGuysDialog
  items:
    buch_PdG: { }
    basic_stick: { hidden: true }
    basic_sword: { hidden: true }
    basic_wine: { hidden: true, amount: 2 }
    basic_cigaretts: { hidden: true, amount: 2 }
  details:
    - name: Small box
      id: trainstation_small-box
      description: 
        - "PERZEPTION;A small wooden box stands in the left corner of the room."
      look: in
      items:
        basic_wine: Wine
        basic_cigaretts: A pack of Cigaretts
        basic_sword: Basic Sword
        basic_stick: Stick
        buch_PdG: Book


- name: Gleise
  id: bahnhof_gleise
  description: 
    - PERZEPTION;Hier ist der Lärm Ohrenbetäubend, die Dampflokomotiven haben den ganzen bereich vernebelt. Schwitzige, ölbeschmierte Arbeiter reparieren notdürftig Züge, reiche Familien rennen in aufwändigen Gewändern ihren Packburschen davon, es herscht wildes Treiben. Richtung Noden liegen die Gleise des Bahnhofs, nach Süden geht es zurück zur Eingangshalle
  exits:
    gleis1: { name: "Gleis 1", prep: zu}
    gleis2: { name: "Gleis 2", prep: zu}
    gleis3: { name: "Gleis 3", prep: zu}
    gleis4: { name: "Gleis 4", prep: zu}
    gleis5: { name: "Gleis 5", prep: zu}
    bahnhof_eingangshalle: { name: Eingangshalle, prep: zur }

- name: Nebenhalle
  id: bahnhof_nebenhalle 
  description: 
    - PERZEPTION;Hier ist es etwas ruhiger und leerer. Aber die Personen hier kommen dir unheimlicher und auch sonderbarer vor. Ah und hier sind auch die Toiletten.
  exits:
    bahnhof_eingangshalle: { name: Eingangshalle, prep: zur}
    bahnhof_toiletten: { name: Toiletten, prep: zu den}
  characters:
    - name: Konstantin Thron
      id: konstantin_thron
      dialog: konstantinDialog
      items:
        basic_cigaretts: { }
        basic_wine: { }
    - name: Passant1
      id: passant4
      description: 
      - "PERZEPTION;Wieder stehen drei Passanten merkwürdig gekleidet in einer Ecke im Norden-Westen und deuten wild umher."
      dialog: strangeGuysDialog
    - name: Passant2
      id: passant5
      dialog: strangeGuysDialog
    - name: Passant3
      id: passant6
      dialog: strangeGuysDialog

- name: Ausgang
  id: ausgang
  description:
  - PERZEPTION;You have left this world
  exits:
    bahnhof_eingangshalle: { name: Eingangshalle }
  characters:

- name: Toiletten
  id: bahnhof_toiletten 
  description: 
    - PERZEPTION;Versifte Toiletten, aber endlich Ruhe, hier scheint niemand zu sein. Zwei Türen führen zu den Männer- bzw. Frauentoiletten. Im Westen geht es zurück ins Nebengebäude.
  exits:
    bahnhof_maennerToilette: { name: Männer-Toilette, prep: zur}
    bahnhof_frauenToilette: { name: Frauen-Toilette, prep: zur}
    bahnhof_nebenhalle: { name: Nebenhalle, prep: zur}
  characters:

- name: Männer-Toilette
  id: bahnhof_maennerToilette
  description: 
    - PERZEPTION;Die Männertoilette, sie ist erstaunlich sauber, in einer Ecke liegen einige zerdrückte Kippenstummel, aber es riecht nicht nach Rauch.
  exits:
    bahnhof_toiletten: { name: Vorraum, prep: zurück zum }
  characters:
    - name: Ticketverkäufer
      id: ticketVerkäufer
      description: 
      - "PERZEPTION;Ein Mann steht offensichtlich leicht betrunken mit hochgezogener Hose am Pissoir und tut nichts außer scheinbar nachzudenken. Du erkennst ihn als die Person, die dir als der Ticketverkäufer beschrieben wurde."
      dialog: ticketVerkäuferDialog

- name: Frauen-Toilette
  id: bahnhof_frauenToilette
  description: 
    - "PERZEPTION;Die Frauentoilette:  es stinkt nach Alkohol, Kippen und Sex. Der Boden ist voller Alkohol und Glasscherben."
  exits:
    bahnhof_toiletten: { name: Vorraum, prep: zurück zum }
  characters:
    - name: Besoffener Frau
      id: besoffene_frau
      description: 
      - "PERZEPTION;Eine besoffene Frau schnarcht laut auf der Toilette. Die Tür steht offen. Dich beschleicht der Gedanke, dass sie für das Chaos, den Geruch und die Scherben verantwortlich ist."
      hp: 40
      strength: 16
      attacks:
        kick: Normal Kick
        punsch: Punsch
      dialog: drunkWomanDialog


- name: "Gleis 1"
  id: gleis1
  description: 
    - PERZEPTION;Hier ist es laut, die Züge fahren in irgendwelche Städte, die du nicht kennst.
  exits: 
    bahnhof_gleise: { name: Zurück zu den Gleisen }
  characters:

- name: "Gleis 2"
  id: gleis2
  description: 
    - PERZEPTION;Hier ist es laut, die Züge fahren in irgendwelche Städte, die du nicht kennst.
  exits: 
    bahnhof_gleise: { name: Zurück zu den Gleisen }
  characters:

- name: "Gleis 3"
  id: gleis3
  description: 
    - PERZEPTION;Ah, Gleis 3. Hier fährt dein Zug nach Moskau. Es ist selbstsam leer.
  exits: 
    bahnhof_gleise: { name: Zurück zu den Gleisen }
  characters:

- name: "Gleis 4"
  id: gleis4
  description: 
    - PERZEPTION;Hier ist es laut, die Züge fahren in irgendwelche Städte, die du nicht kennst.
  exits: 
    bahnhof_gleise: { name: Zurück zu den Gleisen }
  characters:

- name: "Gleis 5"
  id: gleis5
  description: 
    - PERZEPTION;Hier ist es laut, die Züge fahren in irgendwelche Städte, die du nicht kennst.
  exits: 
    bahnhof_gleise: { name: Zurück zu den Gleisen }
  characters:
    - name: Passant1
      id: passant7
      description: 
      - "PERZEPTION;Wieder stehen drei Passanten merkwürdig gekleidet in einer Ecke und deuten wild umher."
      dialog: strangeGuysDialog
    - name: Passant2
      id: passant8
      dialog: strangeGuysDialog
    - name: Passant3
      id: passant9
      dialog: strangeGuysDialog

